### PR TITLE
Refresh consul pack

### PR DESCRIPTION
**Pull request by nzlosh**
We use consul a lot as part of our automatic package upgrade workflow.  The consul pack has some limitations in our use case which we needed to address:

- Added 9 new actions (a few were added just for completeness).
- At least 1 action didn't return all the metadata as returned by the Consul API that we required access to.
- We were slightly frustrated with the naming convention which doesn't follow the Consul API, so to avoid second guessing and making documentation lookup on the python-consul site, we aligned the actions with the Consul API.

**This patch will require re-writes for any workflows that use the consul pack.  Not just for the action name but also for certain actions that will return different data structures.**

I'm offering this patch as-is in the hopes that it will be accepted by the community in large as a cleaner approach to integrating with Consul.

### CODE REVIEW

**Comment by nzlosh** [comment]
FYI, if this patch is accepted it will fix issue #4

**Comment by nzlosh** [comment]
@LindsayHill could we merge to master since there haven't been any major objections?

**Comment by LindsayHill** [comment]
Yep, let's do it

**Comment by Kami** [comment]
Small build failure (lint) - https://circleci.com/gh/StackStorm-Exchange/stackstorm-consul/24?utm_campaign=build-failed&utm_medium=email&utm_source=notification

Will push a fix :)

**Comment by Kami** [comment]
Never mind, I see there already is https://github.com/StackStorm-Exchange/stackstorm-consul/pull/9.

Thanks @LindsayHill

**Pull request merged**
